### ISSUE TITLE
MissingTargetFrameworkException

### ISSUE THREAD

**Issue by MiroslawSlanda** [bennor/AutoT4MVC#15]
I got exception when install AutoT4MVC on Windows 10.

02.05.2015 09:17:47 - Microsoft VSIX Installer
02.05.2015 09:17:47 - -------------------------------------------
02.05.2015 09:17:47 - Initializing Install...
02.05.2015 09:17:48 - Extension Details...
02.05.2015 09:17:48 - 	Identifier      : c676817c-46cc-47d3-b03c-8a05f499d4a5
02.05.2015 09:17:48 - 	Name            : AutoT4MVC
02.05.2015 09:17:48 - 	Author          : Bennor McCarthy
02.05.2015 09:17:48 - 	Version         : 1.5.2
02.05.2015 09:17:48 - 	Description     : An extension for Visual Studio which automatically runs your T4MVC templates at build time and when you create/remove/rename/save a file that T4MVC cares about.
02.05.2015 09:17:48 - 	Locale          : en-US
02.05.2015 09:17:48 - 	MoreInfoURL     : http://bennor.github.io/AutoT4MVC/
02.05.2015 09:17:48 - 	InstalledByMSI  : False
02.05.2015 09:17:48 - 	SupportedFrameworkVersionRange : [4.5]
02.05.2015 09:17:48 - 
02.05.2015 09:17:48 - 	Supported Products : 
02.05.2015 09:17:48 - 		Microsoft.VisualStudio.Pro
02.05.2015 09:17:48 - 			Version : [11.0,14.0]
02.05.2015 09:17:48 - 		Microsoft.VisualStudio.Premium
02.05.2015 09:17:48 - 			Version : [11.0,14.0]
02.05.2015 09:17:48 - 		Microsoft.VisualStudio.Ultimate
02.05.2015 09:17:48 - 			Version : [11.0,14.0]
02.05.2015 09:17:48 - 
02.05.2015 09:17:48 - 	References      : 
02.05.2015 09:17:48 - 
02.05.2015 09:17:48 - Searching for applicable products...
02.05.2015 09:17:48 - Found installed product - Microsoft Visual Studio 2010 Shell - Integrated Mode
02.05.2015 09:17:48 - Found installed product - Microsoft Visual Studio Premium 2013
02.05.2015 09:17:49 - The extension with ID 'c676817c-46cc-47d3-b03c-8a05f499d4a5' is not installed to Microsoft Visual Studio Premium 2013.
02.05.2015 09:17:49 - Found installed product - Microsoft Visual Studio Professional 2013
02.05.2015 09:17:49 - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
02.05.2015 09:17:49 - Found installed product - Global Location
02.05.2015 09:17:49 - Found installed product - ssms
02.05.2015 09:17:50 - The following target products have been selected...
02.05.2015 09:17:50 - 	Microsoft Visual Studio Premium 2013
02.05.2015 09:17:50 - 
02.05.2015 09:17:51 - Beginning to install extension to Microsoft Visual Studio Premium 2013...
02.05.2015 09:17:51 - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'AutoT4MVC' requires a version of the .NET Framework that is not installed.
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForValidDotNetFramework(IExtension extension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.CheckForInstallBlockers(InstallableExtensionImpl extension, IInstalledExtensionList modifiedInstalledExtensionsList, Boolean isNestedExtension, Boolean& olderVersionInstalled)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallInternal(InstallableExtensionImpl extension, Boolean perMachine, Boolean isNestedExtension, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, UInt64 totalBytesToWrite, UInt64& totalBytesWritten)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.BeginInstall(IInstallableExtension installableExtension, Boolean perMachine, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionManagerService.InstallWorker(IInstallableExtension extension, Boolean perMachine, AsyncOperation asyncOp)

**Comment by bennor** [comment]
Will look into it soon. Are you able to tell me which versions of the .NET framework _are_ installed on Win 10?

**Comment by bennor** [comment]
I wasn't able to reproduce it (with VS 2015 RC Community Edition on Windows 10 Insider Preview), but I think I've found a solution. Can you try installing the [VSIX](https://github.com/bennor/AutoT4MVC/releases/download/v1.5.2/AutoT4MVC.vsix), from https://github.com/bennor/AutoT4MVC/releases/tag/v1.5.2 and let me know if it works.

**Comment by MiroslawSlanda** [comment]
Hi,
I removed Windows 10 from my PC because I had many problems with AutoT4MVC, Telerik, WinRT symulator, etc.
Thanks for your reply.

P.S. AutoT4MVC is great tool for me:)

Miroslaw Slanda
Poland
________________________________
Od: Bennor McCarthy [notifications@github.com]
Wysłano: 9 maja 2015 05:38
Do: bennor/AutoT4MVC
DW: Slanda, Miroslaw WSK
Temat: [External] Re: [AutoT4MVC] MissingTargetFrameworkException (#15)


I wasn't able to reproduce it (with VS 2015 RC Community Edition on Windows 10 Insider Preview), but I think I've found a solution. Can you try installing the VSIX<https://github.com/bennor/AutoT4MVC/releases/download/v1.5.2/AutoT4MVC.vsix>, from https://github.com/bennor/AutoT4MVC/releases/tag/v1.5.2 and let me know if it works.
