### ISSUE TITLE
Cannot Find/Install Extension in Visual Studio 2017 RTW

### ISSUE THREAD

**Issue by jdaigle** [bennor/AutoT4MVC#18]
### Affected Version

VisualStudio/15.0.0-RTW+26228.4

### Steps to recreate

1. Install Visual Studio 2017 RTW
2. Open Extensions and Updates
3. Click on Online
4. Search for "AutoT4MVC"
5. The extension is not in the search results

**Comment by bennor** [comment]
Will try to get it sorted in the next couple of days.

**Comment by bennor** [comment]
The latest version (1.5.3), which has support for 2017, has been added to the gallery. It's taking a while to show up though. If you don't want to wait, you can grab the VSIX from the [release](https://github.com/bennor/AutoT4MVC/releases/tag/v1.5.3).
